### ISSUE TITLE
[Question] What's the design philosophy behind AppVars?

### ISSUE THREAD

**Issue by xubury** [IainWinter/IwEngine#4]
Hi Iain, first of all, I want to tell you that I absolutly love your project and youtube videos!
But I have a small question I hope you can explain for me. (I am a noob for coding such large project)
I have been reading your code and can't help notice that a  lot of places use `AppVars`.
Can you explain why you chose such desgin instead of singleton?
Lots of thanks!

**Comment by IainWinter** [comment]
Thanks! I could have used singletons but I like the idea of having them be scoped to the engine pieces of code mainly for readability. You could also have different instances for different layers. For example with the entity system, you could pass a separate Space to a layer and have it not know about the other entities for something like different dimensions.

**Comment by xubury** [comment]
yeah, that make senses. I also find out singleton could have multiple instances when using dynamic linking. Waste me hours to debug.

**Comment by Delofon** [comment]
Singletons in general shouldn't be used to access data. I can go on here why is it like that, but you can ask any other dev or just google it on somewhere like stackoverflow and get the exact same answer repeated over and over again. I will not do that again.
