### ISSUE TITLE
algo/ManifoldFactory.cpp is missing

### ISSUE THREAD

**Issue by Humanagon** [IainWinter/IwEngine#8]
I can't follow along with the 5 minute collision video because the FindSphereSphereCollisionPoints functions and others are missing and I can't find the contents that they're supposed to contain.

**Comment by IainWinter** [comment]
I really didn't like the double dispatch so currently in the repo there is code here: https://github.com/IainWinter/IwEngine/blob/master/IwEngine/src/physics/Collision/TestCollision.cpp

which calls into: https://github.com/IainWinter/IwEngine/blob/master/IwEngine/include/iw/physics/impl/TestCollision.h

based on a table defined here: https://github.com/IainWinter/IwEngine/blob/3e2052855fea85718b7a499a7b1a3befd49d812b/IwEngine/include/iw/physics/impl/TestCollision.h#L25

This solution removes the need for n^2 functions where n is the number of collider types. 

I got the idea for a table of function pointers from page 33 of this valve 
document: http://media.steampowered.com/apps/valve/2015/DirkGregorius_Contacts.pdf
